import machopImg from "@/assets/pokemon/machop.png";
import psyduckImg from "@/assets/pokemon/psyduck.png";
import trapinchImg from "@/assets/pokemon/trapinch.png";
import charmanderImg from "@/assets/pokemon/charmander.png";
import eeveeImg from "@/assets/pokemon/eevee.png";
import porygonImg from "@/assets/pokemon/porygon.png";
import arcanineImg from "@/assets/pokemon/arcanine.png";
import flygonImg from "@/assets/pokemon/flygon.png";
import pikachuImg from "@/assets/pokemon/pikachu.png";
import bulbasaurImg from "@/assets/pokemon/bulbasaur.png";
import type { BattleOpponent } from "./types";

export const MAP_OPPONENTS: BattleOpponent[] = [
  {
    id: "machop",
    name: "Machop",
    trainer: "Lutador do Sparring Ring",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/blackbelt.png",
    level: 18,
    maxHp: 85,
    sprite: machopImg,
    type: "Lutador",
    rewardExp: 45,
    moves: [
      { name: "Golpe de Caratê", type: "Lutador", power: 18 },
      { name: "Rasteira", type: "Lutador", power: 14 },
      { name: "Soco Focado", type: "Lutador", power: 22 },
      { name: "Investida", type: "Normal", power: 12 },
    ],
    team: [
      {
        id: "machop-1",
        name: "Machop",
        level: 18,
        maxHp: 85,
        sprite: machopImg,
        type: "Lutador",
        moves: [
          { name: "Golpe de Caratê", type: "Lutador", power: 18 },
          { name: "Rasteira", type: "Lutador", power: 14 },
          { name: "Soco Focado", type: "Lutador", power: 22 },
        ],
        rewardExp: 45,
      },
      {
        id: "makuhita-2",
        name: "Makuhita",
        level: 19,
        maxHp: 95,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/296.gif",
        type: "Lutador",
        moves: [
          { name: "Tapa Duplo", type: "Normal", power: 16 },
          { name: "Investida Forte", type: "Lutador", power: 20 },
          { name: "Soco Sísmico", type: "Lutador", power: 24 },
        ],
        rewardExp: 50,
      },
      {
        id: "machoke-3",
        name: "Machoke",
        level: 21,
        maxHp: 115,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/67.gif",
        type: "Lutador",
        moves: [
          { name: "Golpe Cruzado", type: "Lutador", power: 28 },
          { name: "Submissão", type: "Lutador", power: 26 },
          { name: "Soco Focado", type: "Lutador", power: 24 },
        ],
        rewardExp: 65,
      },
    ],
  },
  {
    id: "psyduck",
    name: "Psyduck",
    trainer: "Pescadora do Oásis",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/fisherman.png",
    level: 20,
    maxHp: 95,
    sprite: psyduckImg,
    type: "Água",
    rewardExp: 50,
    moves: [
      { name: "Jato d'Água", type: "Água", power: 18 },
      { name: "Confusão Psíquica", type: "Psíquico", power: 22 },
      { name: "Arranhão", type: "Normal", power: 12 },
      { name: "Pulso D'Água", type: "Água", power: 24 },
    ],
    team: [
      {
        id: "psyduck-1",
        name: "Psyduck",
        level: 20,
        maxHp: 95,
        sprite: psyduckImg,
        type: "Água",
        moves: [
          { name: "Jato d'Água", type: "Água", power: 18 },
          { name: "Confusão Psíquica", type: "Psíquico", power: 22 },
          { name: "Pulso D'Água", type: "Água", power: 24 },
        ],
        rewardExp: 50,
      },
      {
        id: "poliwag-2",
        name: "Poliwag",
        level: 19,
        maxHp: 88,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/60.gif",
        type: "Água",
        moves: [
          { name: "Bolhas de Sabão", type: "Água", power: 16 },
          { name: "Pistola D'Água", type: "Água", power: 20 },
          { name: "Hipnose Rápida", type: "Psíquico", power: 14 },
        ],
        rewardExp: 48,
      },
      {
        id: "golduck-3",
        name: "Golduck",
        level: 22,
        maxHp: 110,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/55.gif",
        type: "Água / Psíquico",
        moves: [
          { name: "Hidro Bomba", type: "Água", power: 30 },
          { name: "Confusão Zen", type: "Psíquico", power: 26 },
          { name: "Raio Psíquico", type: "Psíquico", power: 24 },
        ],
        rewardExp: 65,
      },
    ],
  },
  {
    id: "trapinch",
    name: "Trapinch",
    trainer: "Ranger do Santuário",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/hiker.png",
    level: 22,
    maxHp: 110,
    sprite: trapinchImg,
    type: "Terra",
    rewardExp: 55,
    moves: [
      { name: "Tumba de Areia", type: "Terra", power: 22 },
      { name: "Mordida Feroz", type: "Sombrio", power: 20 },
      { name: "Escavação", type: "Terra", power: 26 },
      { name: "Tempestade de Areia", type: "Terra", power: 15 },
    ],
    team: [
      {
        id: "trapinch-1",
        name: "Trapinch",
        level: 22,
        maxHp: 110,
        sprite: trapinchImg,
        type: "Terra",
        moves: [
          { name: "Tumba de Areia", type: "Terra", power: 22 },
          { name: "Mordida Feroz", type: "Sombrio", power: 20 },
          { name: "Escavação", type: "Terra", power: 26 },
        ],
        rewardExp: 55,
      },
      {
        id: "sandshrew-2",
        name: "Sandshrew",
        level: 21,
        maxHp: 95,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/27.gif",
        type: "Terra",
        moves: [
          { name: "Giro Rápido", type: "Normal", power: 18 },
          { name: "Tiro de Lama", type: "Terra", power: 22 },
          { name: "Garra de Areia", type: "Terra", power: 24 },
        ],
        rewardExp: 52,
      },
      {
        id: "vibrava-3",
        name: "Vibrava",
        level: 24,
        maxHp: 120,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/329.gif",
        type: "Dragão / Terra",
        moves: [
          { name: "Sopro do Dragão", type: "Dragão", power: 28 },
          { name: "Terremoto Leve", type: "Terra", power: 26 },
          { name: "Asa Cortante", type: "Voador", power: 22 },
        ],
        rewardExp: 70,
      },
    ],
  },
  {
    id: "charmander",
    name: "Charmander",
    trainer: "Campista Dev",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/camper.png",
    level: 24,
    maxHp: 100,
    sprite: charmanderImg,
    type: "Fogo",
    rewardExp: 58,
    moves: [
      { name: "Brasa", type: "Fogo", power: 20 },
      { name: "Lança-Chamas", type: "Fogo", power: 28 },
      { name: "Garra de Metal", type: "Aço", power: 22 },
      { name: "Arranhão", type: "Normal", power: 14 },
    ],
    team: [
      {
        id: "charmander-1",
        name: "Charmander",
        level: 24,
        maxHp: 100,
        sprite: charmanderImg,
        type: "Fogo",
        moves: [
          { name: "Brasa", type: "Fogo", power: 20 },
          { name: "Lança-Chamas", type: "Fogo", power: 28 },
          { name: "Garra de Metal", type: "Aço", power: 22 },
        ],
        rewardExp: 58,
      },
      {
        id: "growlithe-2",
        name: "Growlithe",
        level: 23,
        maxHp: 105,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/58.gif",
        type: "Fogo",
        moves: [
          { name: "Presa de Fogo", type: "Fogo", power: 24 },
          { name: "Roda Flamejante", type: "Fogo", power: 22 },
          { name: "Investida Veloz", type: "Normal", power: 18 },
        ],
        rewardExp: 55,
      },
      {
        id: "charmeleon-3",
        name: "Charmeleon",
        level: 25,
        maxHp: 125,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/5.gif",
        type: "Fogo",
        moves: [
          { name: "Fúria do Dragão", type: "Dragão", power: 28 },
          { name: "Lança-Chamas Intenso", type: "Fogo", power: 32 },
          { name: "Garra de Metal", type: "Aço", power: 24 },
        ],
        rewardExp: 72,
      },
    ],
  },
  {
    id: "eevee",
    name: "Eevee",
    trainer: "Mecânica de Software",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/lass.png",
    level: 25,
    maxHp: 105,
    sprite: eeveeImg,
    type: "Normal",
    rewardExp: 60,
    moves: [
      { name: "Ataque Rápido", type: "Normal", power: 20 },
      { name: "Mordida", type: "Sombrio", power: 22 },
      { name: "Investida Veloz", type: "Normal", power: 18 },
      { name: "Estrela Cadente", type: "Normal", power: 25 },
    ],
    team: [
      {
        id: "eevee-1",
        name: "Eevee",
        level: 25,
        maxHp: 105,
        sprite: eeveeImg,
        type: "Normal",
        moves: [
          { name: "Ataque Rápido", type: "Normal", power: 20 },
          { name: "Mordida", type: "Sombrio", power: 22 },
          { name: "Estrela Cadente", type: "Normal", power: 25 },
        ],
        rewardExp: 60,
      },
      {
        id: "vaporeon-2",
        name: "Vaporeon",
        level: 25,
        maxHp: 125,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/134.gif",
        type: "Água",
        moves: [
          { name: "Raio Aurora", type: "Gelo", power: 26 },
          { name: "Pulso D'Água", type: "Água", power: 26 },
          { name: "Armadura Ácida", type: "Veneno", power: 18 },
        ],
        rewardExp: 70,
      },
      {
        id: "jolteon-3",
        name: "Jolteon",
        level: 26,
        maxHp: 118,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/135.gif",
        type: "Elétrico",
        moves: [
          { name: "Trovoada", type: "Elétrico", power: 30 },
          { name: "Míssil de Espinhos", type: "Inseto", power: 22 },
          { name: "Onda de Choque", type: "Elétrico", power: 24 },
        ],
        rewardExp: 75,
      },
    ],
  },
  {
    id: "porygon",
    name: "Porygon",
    trainer: "Desenvolvedor da Oficina",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/scientist.png",
    level: 26,
    maxHp: 115,
    sprite: porygonImg,
    type: "Normal",
    rewardExp: 65,
    moves: [
      { name: "Raio Psíquico", type: "Psíquico", power: 26 },
      { name: "Tri-Ataque", type: "Normal", power: 30 },
      { name: "Canhão de Choque", type: "Elétrico", power: 24 },
      { name: "Conversão Digital", type: "Normal", power: 16 },
    ],
    team: [
      {
        id: "porygon-1",
        name: "Porygon",
        level: 26,
        maxHp: 115,
        sprite: porygonImg,
        type: "Normal",
        moves: [
          { name: "Raio Psíquico", type: "Psíquico", power: 26 },
          { name: "Tri-Ataque", type: "Normal", power: 30 },
          { name: "Canhão de Choque", type: "Elétrico", power: 24 },
        ],
        rewardExp: 65,
      },
      {
        id: "magneton-2",
        name: "Magneton",
        level: 25,
        maxHp: 110,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/82.gif",
        type: "Elétrico / Aço",
        moves: [
          { name: "Canhão de Luz", type: "Aço", power: 26 },
          { name: "Descarga Elétrica", type: "Elétrico", power: 28 },
          { name: "Bomba Sonora", type: "Normal", power: 20 },
        ],
        rewardExp: 68,
      },
      {
        id: "porygon2-3",
        name: "Porygon2",
        level: 27,
        maxHp: 130,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/233.gif",
        type: "Normal",
        moves: [
          { name: "Tri-Ataque Avançado", type: "Normal", power: 34 },
          { name: "Hiper Raio Digital", type: "Normal", power: 38 },
          { name: "Psíquico Quântico", type: "Psíquico", power: 30 },
        ],
        rewardExp: 80,
      },
    ],
  },
  {
    id: "arcanine",
    name: "Arcanine",
    trainer: "Mestre da Arena",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/veteran.png",
    level: 28,
    maxHp: 140,
    sprite: arcanineImg,
    type: "Fogo",
    rewardExp: 75,
    moves: [
      { name: "Lança-Chamas", type: "Fogo", power: 30 },
      { name: "Velocidade Extrema", type: "Normal", power: 25 },
      { name: "Presa de Fogo", type: "Fogo", power: 24 },
      { name: "Roda de Fogo", type: "Fogo", power: 22 },
    ],
    team: [
      {
        id: "arcanine-1",
        name: "Arcanine",
        level: 28,
        maxHp: 140,
        sprite: arcanineImg,
        type: "Fogo",
        moves: [
          { name: "Lança-Chamas", type: "Fogo", power: 30 },
          { name: "Velocidade Extrema", type: "Normal", power: 25 },
          { name: "Presa de Fogo", type: "Fogo", power: 24 },
        ],
        rewardExp: 75,
      },
      {
        id: "rapidash-2",
        name: "Rapidash",
        level: 27,
        maxHp: 120,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/78.gif",
        type: "Fogo",
        moves: [
          { name: "Pisoteio de Fogo", type: "Fogo", power: 26 },
          { name: "Roda de Chamas", type: "Fogo", power: 24 },
          { name: "Ataque Ágil", type: "Normal", power: 20 },
        ],
        rewardExp: 70,
      },
      {
        id: "ninetales-3",
        name: "Ninetales",
        level: 29,
        maxHp: 135,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/38.gif",
        type: "Fogo",
        moves: [
          { name: "Onda de Calor", type: "Fogo", power: 34 },
          { name: "Fogo Fátuo Místico", type: "Fogo", power: 28 },
          { name: "Poder Oculto", type: "Psíquico", power: 26 },
        ],
        rewardExp: 85,
      },
    ],
  },
  {
    id: "flygon",
    name: "Flygon Lendário",
    trainer: "Viajante do Deserto",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/brendan.png",
    level: 32,
    maxHp: 165,
    sprite: flygonImg,
    type: "Dragão / Terra",
    rewardExp: 90,
    moves: [
      { name: "Respiração do Dragão", type: "Dragão", power: 32 },
      { name: "Terremoto da Areia", type: "Terra", power: 35 },
      { name: "Asa de Aço", type: "Aço", power: 26 },
      { name: "Hiper Raio Místico", type: "Normal", power: 40 },
    ],
    team: [
      {
        id: "flygon-1",
        name: "Flygon Lendário",
        level: 32,
        maxHp: 165,
        sprite: flygonImg,
        type: "Dragão / Terra",
        moves: [
          { name: "Respiração do Dragão", type: "Dragão", power: 32 },
          { name: "Terremoto da Areia", type: "Terra", power: 35 },
          { name: "Hiper Raio Místico", type: "Normal", power: 40 },
        ],
        rewardExp: 90,
      },
      {
        id: "garchomp-2",
        name: "Garchomp",
        level: 33,
        maxHp: 175,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/445.gif",
        type: "Dragão / Terra",
        moves: [
          { name: "Garra do Dragão", type: "Dragão", power: 34 },
          { name: "Terremoto Sísmico", type: "Terra", power: 36 },
          { name: "Meteoro do Dragão", type: "Dragão", power: 42 },
        ],
        rewardExp: 95,
      },
      {
        id: "salamence-3",
        name: "Salamence",
        level: 34,
        maxHp: 180,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/373.gif",
        type: "Dragão / Voador",
        moves: [
          { name: "Sopro Dracônico", type: "Dragão", power: 36 },
          { name: "Golpe Aéreo", type: "Voador", power: 30 },
          { name: "Hiper Raio Titânico", type: "Normal", power: 45 },
        ],
        rewardExp: 100,
      },
    ],
  },
  {
    id: "pikachu",
    name: "Pikachu & Raichu",
    trainer: "Guia da Cidade",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/acetrainerf.png",
    level: 22,
    maxHp: 105,
    sprite: pikachuImg,
    type: "Elétrico",
    rewardExp: 55,
    moves: [
      { name: "Choque do Trovão", type: "Elétrico", power: 24 },
      { name: "Ataque Rápido", type: "Normal", power: 22 },
      { name: "Investida Trovão", type: "Elétrico", power: 28 },
      { name: "Cauda de Ferro", type: "Aço", power: 25 },
    ],
    team: [
      {
        id: "pikachu-opp-1",
        name: "Pikachu",
        level: 22,
        maxHp: 105,
        sprite: pikachuImg,
        type: "Elétrico",
        moves: [
          { name: "Choque do Trovão", type: "Elétrico", power: 24 },
          { name: "Ataque Rápido", type: "Normal", power: 22 },
          { name: "Investida Trovão", type: "Elétrico", power: 28 },
        ],
        rewardExp: 55,
      },
      {
        id: "raichu-opp-2",
        name: "Raichu",
        level: 25,
        maxHp: 125,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/26.gif",
        type: "Elétrico",
        moves: [
          { name: "Trovão Fulminante", type: "Elétrico", power: 38 },
          { name: "Onda de Choque", type: "Elétrico", power: 30 },
          { name: "Pancada Forte", type: "Normal", power: 26 },
        ],
        rewardExp: 75,
      },
    ],
  },
  {
    id: "merchant",
    name: "Kecleon & Meowth",
    trainer: "Mercador do Bazar",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/gentleman.png",
    level: 24,
    maxHp: 120,
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/352.gif",
    type: "Normal / Noturno",
    rewardExp: 65,
    moves: [
      { name: "Pulso Sombrio", type: "Noturno", power: 30 },
      { name: "Ataque Rápido", type: "Normal", power: 22 },
      { name: "Mordida Sinistra", type: "Noturno", power: 26 },
      { name: "Pancada Forte", type: "Normal", power: 28 },
    ],
    team: [
      {
        id: "meowth-opp-1",
        name: "Meowth",
        level: 22,
        maxHp: 95,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/52.gif",
        type: "Normal",
        moves: [
          { name: "Arranhão Certeiro", type: "Normal", power: 20 },
          { name: "Mordida Rápida", type: "Noturno", power: 22 },
          { name: "Golpe de Fúria", type: "Normal", power: 24 },
        ],
        rewardExp: 50,
      },
      {
        id: "kecleon-opp-2",
        name: "Kecleon",
        level: 24,
        maxHp: 120,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/352.gif",
        type: "Normal / Noturno",
        moves: [
          { name: "Pulso Sombrio", type: "Noturno", power: 30 },
          { name: "Ataque Furtivo", type: "Noturno", power: 25 },
          { name: "Pancada Camuflada", type: "Normal", power: 28 },
        ],
        rewardExp: 65,
      },
      {
        id: "persian-opp-3",
        name: "Persian",
        level: 26,
        maxHp: 130,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/53.gif",
        type: "Normal",
        moves: [
          { name: "Garra Cortante", type: "Normal", power: 30 },
          { name: "Jóia do Poder", type: "Pedra", power: 32 },
          { name: "Hiper Raio", type: "Normal", power: 40 },
        ],
        rewardExp: 80,
      },
    ],
  },
  {
    id: "bulbasaur",
    name: "Bulbasaur Guardião",
    trainer: "Pesquisador do Oásis",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/scientist.png",
    level: 23,
    maxHp: 110,
    sprite: bulbasaurImg,
    type: "Planta / Veneno",
    rewardExp: 60,
    moves: [
      { name: "Chicote de Vinha", type: "Planta", power: 24 },
      { name: "Bomba de Lodo", type: "Veneno", power: 32 },
      { name: "Folha Navalha", type: "Planta", power: 26 },
      { name: "Pó Venenoso", type: "Veneno", power: 22 },
    ],
    team: [
      {
        id: "bulbasaur-opp-1",
        name: "Bulbasaur",
        level: 23,
        maxHp: 110,
        sprite: bulbasaurImg,
        type: "Planta / Veneno",
        moves: [
          { name: "Chicote de Vinha", type: "Planta", power: 24 },
          { name: "Bomba de Lodo", type: "Veneno", power: 32 },
          { name: "Folha Navalha", type: "Planta", power: 26 },
          { name: "Pó Venenoso", type: "Veneno", power: 22 },
        ],
        rewardExp: 60,
      },
      {
        id: "ivysaur-opp-2",
        name: "Ivysaur",
        level: 26,
        maxHp: 135,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/2.gif",
        type: "Planta / Veneno",
        moves: [
          { name: "Raio Solar", type: "Planta", power: 38 },
          { name: "Bomba de Lodo Pesada", type: "Veneno", power: 34 },
          { name: "Chicote Gigante", type: "Planta", power: 28 },
          { name: "Esporos Tóxicos", type: "Veneno", power: 24 },
        ],
        rewardExp: 80,
      },
    ],
  },
  {
    id: "chansey",
    name: "Chansey da Paz",
    trainer: "Hoteleira do Oásis",
    trainerAvatar: "https://play.pokemonshowdown.com/sprites/trainers/beauty.png",
    level: 25,
    maxHp: 160,
    sprite:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/113.gif",
    type: "Normal / Fada",
    rewardExp: 75,
    moves: [
      { name: "Brilho Mágico", type: "Fada", power: 28 },
      { name: "Pancada Suave", type: "Normal", power: 24 },
      { name: "Voz Desarmante", type: "Fada", power: 26 },
      { name: "Hiper Raio", type: "Normal", power: 38 },
    ],
    team: [
      {
        id: "chansey-opp-1",
        name: "Chansey",
        level: 25,
        maxHp: 160,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/113.gif",
        type: "Normal / Fada",
        moves: [
          { name: "Brilho Mágico", type: "Fada", power: 28 },
          { name: "Pancada Suave", type: "Normal", power: 24 },
          { name: "Voz Desarmante", type: "Fada", power: 26 },
          { name: "Hiper Raio", type: "Normal", power: 38 },
        ],
        rewardExp: 75,
      },
      {
        id: "blissey-opp-2",
        name: "Blissey",
        level: 28,
        maxHp: 190,
        sprite:
          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/242.gif",
        type: "Normal / Fada",
        moves: [
          { name: "Explosão Mágica", type: "Fada", power: 36 },
          { name: "Hiper Raio Cósmico", type: "Normal", power: 42 },
          { name: "Luz Suave", type: "Fada", power: 28 },
        ],
        rewardExp: 90,
      },
    ],
  },
];

export const getOpponent = (id: string): BattleOpponent | undefined =>
  MAP_OPPONENTS.find((opponent) => opponent.id === id);
